name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: linuxmint/github-actions/.github/workflows/do-builds.yml@master
    with:
      commit_id: master
      ############################## Comma separated list - like 'linuxmint/xapp, linuxmint/cinnamon-desktop'
      dependencies: 
        linuxmint/cinnamon-control-center,
        linuxmint/cinnamon-desktop,
        linuxmint/cinnamon-menus,
        linuxmint/cinnamon-screensaver,
        linuxmint/cinnamon-session,
        linuxmint/cinnamon-settings-daemon,
        linuxmint/cinnamon-translations,
        linuxmint/cjs,
        linuxmint/glib2.0,
        linuxmint/gnome-desktop,
        linuxmint/gnome-icon-theme,
        linuxmint/gnome-icon-theme-symbolic,
        linuxmint/gsettings-desktop-schemas,
        linuxmint/libcinnamon,
        linuxmint/libcinnamon-menu,
        linuxmint/libgweather,
        linuxmint/linuxmint-keyring,
        linuxmint/muffin,
        linuxmint/nemo,
        linuxmint/nemo-extensions,
        linuxmint/nemo-fileroller,
        linuxmint/nemo-image-converter,
        linuxmint/nemo-media-columns,
        linuxmint/nemo-python,
        linuxmint/nemo-share,
        linuxmint/nemo-terminal,
        linuxmint/nemo-preview,
        linuxmint/nemo-quick-look,
        linuxmint/nemo-seahorse,
        linuxmint/nemo-vcs,
        linuxmint/nemo-xml-tools,
        linuxmint/nemo-extensions,
        linuxmint/nemo-fileroller,
        linuxmint/nemo-image-converter,
        linuxmint/nemo-media-columns,
        linuxmint/nemo-python,
        linuxmint/nemo-share,
        linuxmint/nemo-terminal,
        linuxmint/nemo-preview,
        linuxmint/nemo-quick-look,
        linuxmint/nemo-seahorse,
        linuxmint/nemo-vcs,
        linuxmint/nemo-xml-tools,
        linuxmint/nemo-extensions,
        linuxmint/nemo-fileroller,
        linuxmint/nemo-image-converter,
        linuxmint/nemo-media-columns,
        linuxmint/nemo-python,
        linuxmint/nemo-share,
        linuxmint/nemo-terminal,
        linuxmint/nemo-preview,
        linuxmint/nemo-quick-look,
        linuxmint/nemo-seahorse,
        linuxmint/nemo-vcs,
        linuxmint/nemo-xml-tools,
        linuxmint/nemo-extensions,
        linuxmint/nemo-fileroller,
        linuxmint/nemo-image-converter,
        linuxmint/nemo-media-columns,
        linuxmint/nemo-python,
        linuxmint/nemo-share,
        linuxmint/nemo-terminal,
        linuxmint/nemo-preview,
        linuxmint/nemo-quick-look,
        linuxmint/xapp
      ##############################
